name: mapu_mw
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  url_launcher: ^6.2.3
  connectivity_plus: ^3.0.6
  flutter_no_internet_widget: ^1.0.0+18-dev.1
  flutter_advanced_drawer: ^1.3.5
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  path_provider: ^2.1.2
  flutter_pdfview: ^1.3.2
  flutter_cache_manager: ^3.1.2
  open_file: ^3.2.1
  pdf: ^3.10.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.13.1
  #change_app_package_name: ^0.1.3
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Untitled design (7).png"
  min_sdk_android: 21 
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - lib/Images/Mzuzu_university_logo.jpeg
    - lib/Images/Luarnar.jpg
    - lib/Images/Mubas.jpg
    - lib/Images/MustLOGO.jpg
    - lib/Images/Mzuzu_university_logo.jpeg
    - lib/Images/Unima.jpg
    - lib/Images/Kuhes.jpg
    - lib/Images/gala_TEST_01.jpg
    - lib/KUHES/Pg_photos/Kuhes_cover.jpg
    #- lib/DeveloperPhotos/Rever.jpg
    - lib/Images/MustBack.jpg
    - lib/KUHES/Pg_photos/Mubas_cover.jpg
    - lib/Images/Screenshot_20240116_210628_Chrome.jpg
    - lib/Images/Screenshot_20240116_220922_Chrome.jpg
    - lib/Images/malaw.jpg
    - lib/Images/Mzuzu_university_logo222.jpg
    - lib/Images/MustLOGO-copy.jpg
    #- lib/PDF_files/NCHE-CallForApplications-2023 (1).pdf
    - lib/Images/Screenshot_20240205_073451_Gallery.jpg
